version: '3.4'

services:
  postgres:
    container_name: postgres
    environment:
        POSTGRES_DB: postgres
        POSTGRES_USER: CBSV2_KEYCLOAK
        POSTGRES_PASSWORD: CBSV2_KEYCLOAK
    restart: always
    ports:
        - "5432:5432"
    volumes:
        - postgres_data:/var/lib/postgresql/data/
    networks:
        - nxt

  pgadmin:
    container_name: pgadmin
    environment:
        PGADMIN_DEFAULT_EMAIL : admin@nexturn.com
        PGADMIN_DEFAULT_PASSWORD : admin1234
    ports:
      - "5050:80"
    networks: 
      - nxt

  cbsv2poc.keycloakserver:
    container_name: cbsv2poc.keycloakserver
    environment:
        KC_DB: postgres
        KC_DB_URL: jdbc:postgresql://postgres:5432/postgres 
        KC_DB_USERNAME: CBSV2_KEYCLOAK
        KC_DB_SCHEMA: public
        KC_DB_PASSWORD: CBSV2_KEYCLOAK
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: password
    command: 
     - start-dev --auto-build
    ports:
        - "8080:8080"
    depends_on:
        - postgres
    networks:
        - nxt
    
networks:
   nxt:
    driver: bridge
    external: true
